### ISSUE TITLE
pom.xml 重复的 dependences 标签

### ISSUE THREAD

**Issue by dongshuaige** [fuzhengwei/java-algorithms#2]

**Comment by dongshuaige** [comment]
<dependencies>
        <dependency>
            <groupId>com.alibaba</groupId>
            <artifactId>fastjson</artifactId>
            <version>1.2.75</version>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <compilerVersion>1.8</compilerVersion>
                    <source>1.8</source>
                    <target>1.8</target>
                </configuration>
            </plugin>
        </plugins>
    </build>
    <dependencies>
        <dependency>
            <groupId>junit</groupId>
            <artifactId>junit</artifactId>
            <version>4.12</version>
            <scope>test</scope>
        </dependency>
    </dependencies>

**Comment by fuzhengwei** [comment]
赞 哈哈哈 下次也可以提交 PR 这样能有你的记录在仓库，让我们一起完成这个项目。
